<?php

// This file has been auto-generated by the Symfony Dependency Injection Component for internal use.

if (\class_exists(\Container5sjo2UL\App_KernelDevDebugContainer::class, false)) {
    // no-op
} elseif (!include __DIR__.'/Container5sjo2UL/App_KernelDevDebugContainer.php') {
    touch(__DIR__.'/Container5sjo2UL.legacy');

    return;
}

if (!\class_exists(App_KernelDevDebugContainer::class, false)) {
    \class_alias(\Container5sjo2UL\App_KernelDevDebugContainer::class, App_KernelDevDebugContainer::class, false);
}

return new \Container5sjo2UL\App_KernelDevDebugContainer([
    'container.build_hash' => '5sjo2UL',
    'container.build_id' => '4033b031',
    'container.build_time' => 1648477432,
], __DIR__.\DIRECTORY_SEPARATOR.'Container5sjo2UL');
